config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "presentation#index"

  resources :presentation, only: %w(index show)
  namespace :manage do
    resource :user, only: %w(show update)
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/technology.rb
class Technology < ApplicationRecord
  belongs_to :user

  MAX_LEVEL = 5
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :validatable

  has_many :technologies

  def full_name
    "#{first_name} #{last_name} [#{github_name}]"
  end

  def technologies_title
    technologies.map(&:title).join(', ')
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/presentation_controller.rb
class PresentationController < ApplicationController
  def index
    @users = User.all.limit(10)
  end

  def show
    @user = User.find(params[:id])
    @github_records = github_records(params[:id])
  end

  private

  def github_records(user_id)
    user = User.find(user_id)
    return [] unless user&.github_name.present? || user.nil?
    uri = URI.parse("https://api.github.com/users/#{user.github_name}/repos?sort=updated&per_page=10")
    response = Net::HTTP.get_response(uri)
    return JSON.parse(response.body)
  rescue
    return []
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_login_icon.slim
- if current_user.nil?
  .links
    = link_to 'Logowanie', new_user_session_path, class: 'btn btn-light'
- else
  .links
    = link_to "Konto", manage_user_path, class: 'btn btn-light mr-1'
    = link_to "Wyloguj", destroy_user_session_path, method: :delete, class: 'btn btn-light'

app/views/layouts/_notification.slim
- if notice.present?
  p.alert.alert-primary = notice

- if alert.present?
  p.alert.alert-danger = alert

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Self Presentation</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body id="blue-body">
    <div id="content" class="container">
      <%= render partial: 'layouts/login_icon' %>
      <%= render partial: 'layouts/notification' %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/presentation/index.slim
div.row
  - @users.each do |user|
    .col-4 = link_to user.email, presentation_path(user.id)

  - if @users.empty?
    .col-12.text-center Empty

app/views/presentation/show.slim
div.row
  div.col-6.right-border
    h3 = @user.full_name
    p
      | Stanowisko: 
      b = @user.job_title

    p
      | Technologie: 
      b = @user.technologies_title

    div
      | Poziom doświadczenia
      ul
        - @user.technologies.each do |technology|
          li
            | #{technology.title} 
            - technology.level.times do
              = image_tag 'star-fill', class: 'mr-1'
            - (Technology::MAX_LEVEL - technology.level).times do
              = image_tag 'star', class: 'mr-1'

  div.col-6
    - if @github_records.any?
      table.table
        thead
          tr
            th
            th name
            th created at
            th updated at
        tbody
          - @github_records.each do |record|
            tr
              td = image_tag(record["owner"]["avatar_url"], class: 'xs-image')
              td = record["name"]
              td = record["created_at"].to_date
              td = record["updated_at"].to_date
    - else
      h3.text-center No repositories